# Generated by Django 4.2.3 on 2023-07-14 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('rawTitle', models.CharField(max_length=255)),
                ('rawText', models.TextField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('genre', models.TextField(null=True)),
                ('sysCPU', models.TextField(null=True)),
                ('sysGPU', models.TextField(null=True)),
                ('sysRAM', models.CharField(max_length=255)),
                ('ratingCritics', models.IntegerField(null=True)),
                ('ratingUsers', models.IntegerField(null=True)),
                ('screenshotsFilenames', models.TextField(null=True)),
                ('screenshotsSelected', models.TextField(null=True)),
                ('videoURL', models.CharField(max_length=255)),
                ('videoFilename', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateTimeField(null=True)),
            ],
        )
    ]
