# Generated by Django 4.2.3 on 2023-07-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_weekly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
