# Generated by Django 4.2.3 on 2023-07-31 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_genre_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(unique=True)),
                ('score', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
            ],
        ),
        migrations.CreateModel(
            name='SteamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.BooleanField(default=True)),
                ('url', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('text', models.TextField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
            ],
        ),
    ]
